#define CATCH_CONFIG_RUNNER
#include "catch.hpp"

int main(int argc, char* argv[]) {
  using std::cout;
  cout << "\nWelcome to the Wet 2 Data structures tests                          \n"
          "The tests were written by: Vova Parakhin.                           \n\n"
          "------Passing those tests won't guarantee you a good grade------      \n"
          "But they might get you closer :)                                      \n"
          "You can change w/e you want in the file itself but make sure          \n"
          "to contact me if you want to upload \'upgraded version\' of the file. \n"
          "                                                                    \n\n"
          "              _                                                       \n"
          "             | |                                                      \n"
          "             | |===( )   //////                                       \n"
          "             |_|   |||  | o o|                                        \n"
          "                    ||| ( c  )                  ____                  \n"
          "                     ||| \\= /                  ||   \\_              \n"
          "                      ||||||                   ||     |               \n"
          "                      ||||||                ...||__/|-\"              \n"
          "                      ||||||             __|________|__               \n"
          "                        |||             |______________|              \n"
          "                        |||             |    ENTER     |              \n"
          "                        |||             |______________|              \n"
          "                        |||             || ||      || ||              \n"
          "                        |||             || ||      || ||              \n"
          "------------------------|||-------------||-||------||-||-------       \n"
          "                        |__>            || ||      || ||              \n"
          "                                                                      \n"
          "                                                                      \n"
          "\033[1;31m            SMASH ENTER to continue             \033[0m     \n";
  getchar();
  int result = Catch::Session().run(argc, argv);
  cout << "  __    __       ___      .______   .______   ____    ____            \n"
          " |  |  |  |     /   \\     |   _  \\  |   _   \\ \\   \\  /   /       \n"
          " |  |__|  |    /  ^  \\    |  |_)  | |  |_)  |  \\   \\/   /          \n"
          " |   __   |   /  /_\\  \\   |   ___/  |   ___/    \\_    _/           \n"
          " |  |  |  |  /  _____  \\  |  |      |  |          |  |               \n"
          " |__|  |__| /__/     \\__\\ | _|      | _|          |__|              \n"
          "                                                                      \n"
          "  .__   __.  ___________    __    ____                                \n"
          "  |  \\ |  | |   ____\\   \\  /  \\  /   /                            \n"
          "  |   \\|  | |  |__   \\   \\/    \\/   /                             \n"
          "  |  . `  | |   __|   \\            /                                 \n"
          "  |  |\\   | |  |____   \\    /\\    /                                \n"
          "  |__| \\__| |_______|   \\__/  \\__/                                 \n"
          "                                                                      \n"
          "  ____    ____  _______     ___      .______                          \n"
          "  \\   \\  /   / |   ____|   /   \\     |   _  \\                     \n"
          "   \\   \\/   /  |  |__     /  ^  \\    |  |_)  |                     \n"
          "    \\_    _/   |   __|   /  /_\\  \\   |      /                      \n"
          "      |  |     |  |____ /  _____  \\  |  |\\  \\----.                 \n"
          "      |__|     |_______/__/     \\__\\ | _| `._____|                  \n";
  return 0;
}